//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsWeek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fixture()
        {
            this.Comments = new HashSet<Comment>();
            this.CricketScores = new HashSet<CricketScore>();
            this.deliveries = new HashSet<delivery>();
            this.Match_Events = new HashSet<Match_Events>();
            this.FixturesImages = new HashSet<FixturesImage>();
            this.GoalBaseScores = new HashSet<GoalBaseScore>();
            this.ManOfTheMatches = new HashSet<ManOfTheMatch>();
            this.PointsBaseScores = new HashSet<PointsBaseScore>();
            this.scorecards = new HashSet<scorecard>();
            this.TurnBaseGames = new HashSet<TurnBaseGame>();
        }
    
        public int id { get; set; }
        public Nullable<int> team1_id { get; set; }
        public Nullable<int> team2_id { get; set; }
        public Nullable<System.DateTime> matchDate { get; set; }
        public string venue { get; set; }
        public string match_type { get; set; }
        public Nullable<int> winner_id { get; set; }
        public Nullable<int> sessionSport_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CricketScore> CricketScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery> deliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match_Events> Match_Events { get; set; }
        public virtual SessionSport SessionSport { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixturesImage> FixturesImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoalBaseScore> GoalBaseScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManOfTheMatch> ManOfTheMatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointsBaseScore> PointsBaseScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scorecard> scorecards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnBaseGame> TurnBaseGames { get; set; }
    }
}
