//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsWeek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> fixture_id { get; set; }
        public Nullable<byte> isRead { get; set; }
    
        public virtual Fixture Fixture { get; set; }
        public virtual User User { get; set; }
    }
}
