//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsWeek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string reg_no { get; set; }
        public int team_id { get; set; }
        public int id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Team Team { get; set; }
    }
}
